# --- Input

variable "identifier" {
  type        = string
  description = "The RDS instance identifier"
  default     = "default-identifier"
}

variable "engine_version" {
  type        = string
  description = "The version of the database engine"
  default     = "default-version"
}

variable "db_name" {
  type        = string
  description = "The name of the database"
  default     = "default-db"
}

variable "engine" {
  type        = string
  description = "The database engine to use"
  default     = "postgres"
}

variable "family" {
  type        = string
  description = "The parameter group family name"
  default     = "default-family"
}

variable "instance_class" {
  type        = string
  description = "The instance type of the RDS instance"
  default     = "db.t2.micro"
}

variable "vpc_security_group_ids" {
  type        = list(string)
  description = "A list of VPC security group IDs"
  default     = []
}

variable "subnet_ids" {
  type        = list(string)
  description = "A list of subnet IDs"
  default     = []
}

# --- Config

resource "random_pet" "db_instance" {
  length = 2
}

resource "random_pet" "db_user" {
  length = 1
}

resource "random_password" "db_password" {
  length  = 16
  special = true
}

# --- Output

output "db_instance_address" {
  description = "The address of the RDS instance"
  value       = "${random_pet.db_instance.id}.mock-rds.com"
}

output "db_instance_port" {
  description = "The port on which the DB accepts connections"
  value       = 5432
}

output "db_instance_uname" {
  description = "The database user name"
  value       = random_pet.db_user.id
}

output "db_instance_password" {
  description = "The autogenerated password for the RDS instance"
  value       = random_password.db_password.result
  sensitive = true
}
