// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	terrariumpb "github.com/cldcvr/terrarium/src/pkg/pb/terrariumpb"
)

// TerrariumServiceServer is an autogenerated mock type for the TerrariumServiceServer type
type TerrariumServiceServer struct {
	mock.Mock
}

// HealthCheck provides a mock function with given fields: _a0, _a1
func (_m *TerrariumServiceServer) HealthCheck(_a0 context.Context, _a1 *emptypb.Empty) (*emptypb.Empty, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty) (*emptypb.Empty, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty) *emptypb.Empty); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListModuleAttributes provides a mock function with given fields: _a0, _a1
func (_m *TerrariumServiceServer) ListModuleAttributes(_a0 context.Context, _a1 *terrariumpb.ListModuleAttributesRequest) (*terrariumpb.ListModuleAttributesResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *terrariumpb.ListModuleAttributesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *terrariumpb.ListModuleAttributesRequest) (*terrariumpb.ListModuleAttributesResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *terrariumpb.ListModuleAttributesRequest) *terrariumpb.ListModuleAttributesResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*terrariumpb.ListModuleAttributesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *terrariumpb.ListModuleAttributesRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListModules provides a mock function with given fields: _a0, _a1
func (_m *TerrariumServiceServer) ListModules(_a0 context.Context, _a1 *terrariumpb.ListModulesRequest) (*terrariumpb.ListModulesResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *terrariumpb.ListModulesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *terrariumpb.ListModulesRequest) (*terrariumpb.ListModulesResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *terrariumpb.ListModulesRequest) *terrariumpb.ListModulesResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*terrariumpb.ListModulesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *terrariumpb.ListModulesRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedTerrariumServiceServer provides a mock function with given fields:
func (_m *TerrariumServiceServer) mustEmbedUnimplementedTerrariumServiceServer() {
	_m.Called()
}

// NewTerrariumServiceServer creates a new instance of TerrariumServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTerrariumServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TerrariumServiceServer {
	mock := &TerrariumServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
