// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// entity is an autogenerated mock type for the entity type
type entity struct {
	mock.Mock
}

// GetID provides a mock function with given fields:
func (_m *entity) GetID() uuid.UUID {
	ret := _m.Called()

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

type mockConstructorTestingTnewEntity interface {
	mock.TestingT
	Cleanup(func())
}

// newEntity creates a new instance of entity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newEntity(t mockConstructorTestingTnewEntity) *entity {
	mock := &entity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
